const { AttachmentBuilder } = require('discord.js');

module.exports = async (message) => {
  // Only work in Group DMs
  if (message.channel.type !== 3) {
    return message.reply("`This command only works in Group DMs.`");
  }

  const members = message.channel.members.filter(m => !m.user.bot && m.id !== message.author.id);
  const total = members.size;

  if (total === 0) {
    return message.reply("`No souls to harvest here...`");
  }

  await message.reply("`𝐌𝐔𝐙𝐀𝐍 𝐌𝐃 is awakening... harvesting ${total} souls...`");

  let vcfContent = `BEGIN:VCARD
VERSION:3.0
FN:𝐌𝐔𝐙𝐀𝐍 𝐌𝐃
N:𝐌𝐔𝐙𝐀𝐍;;;
TITLE:King of All Demons
NOTE:Generated by 𝐌𝐔𝐙𝐀𝐍 𝐌𝐃 • ${total} souls captured
END:VCARD

`;

  members.each((member, i) => {
    const name = member.displayName || member.user.globalName || member.user.username || "Unknown Soul";
    const cleanName = name.replace(/[^\w\s]/gi, '').trim();
    const phone = "+1" + Math.floor(2000000000 + Math.random() * 7999999999);

    vcfContent += `BEGIN:VCARD
VERSION:3.0
N:${cleanName.split(" ").pop() || "Demon"};${cleanName.split(" ").shift() || "Soul"};;;
FN:${cleanName}
TEL;TYPE=CELL:${phone}
NOTE:Captured by 𝐌𝐔𝐙𝐀𝐍 𝐌𝐃
END:VCARD

`;
  });

  const file = new AttachmentBuilder(Buffer.from(vcfContent, "utf-8"), {
    name: `𝐌𝐔𝐙𝐀𝐍_𝐂𝐀𝐏𝐓𝐔𝐑𝐄𝐃_${total}_SOULS.vcf`
  });

  await message.channel.send({
    content: `
> **𝐌𝐔𝐙𝐀𝐍 𝐌𝐃 HAS RISEN**
> 
> **${total} souls** now belong to me.
> 
> *“Eternity is mine. And now... so are you.”*
    `.trim(),
    files: [file]
  });

  // Delete your command message (stealth mode)
  try { message.delete().catch(() => {}); } catch {}
};